server:
  port: 7001
eureka:
  instance:
    hostname: localhost # eureka 服务端实例名称
  client:
    register-with-eureka: false   # false 表示不像注册中心注册自己
    fetch-registry: false # false 表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    # 设置与 Eureka server 交互的地址，查询服务和注册服务都需要依赖这个地址。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
