server:
  port: 8001
spring:
  application:
    name: springcloud-payment
eureka:
  client:
    service-url:
      defaultZone: http://10.37.129.13:7001/eureka/
      # 是否从 eureka-server 抓取已有注册信息，默认为 true 。单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡。
    fetch-registry: true
    # 注册到 eureka-server
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 10
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 设置实例名称
    prefer-ip-address: true # 显示 ip 地址信息