server:
  port: 9001
spring:
  application:
    name: ribbon-order-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      # 是否从 eureka-server 抓取已有注册信息，默认为 true 。单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡。
    fetch-registry: true
    # 注册到 eureka-server
    register-with-eureka: true
  instance:
    instance-id: ribbon-order-service-9001 # 设置实例名称
    prefer-ip-address: true # 显示 ip 地址信息
logging:
  config: classpath:logback-dev.xml